import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const SEED_DATA = [
  {
    name: "Healthcare & Medical Services",
    slug: "healthcare",
    subs: [
      { name: "Visit Doctor",             slug: "visit-doctor" },
      { name: "General Physician",        slug: "general-physician" },
      { name: "Specialist Doctor",        slug: "specialist-doctor" },
      { name: "Home Nurse",               slug: "home-nurse" },
      { name: "ICU Nurse",                slug: "icu-nurse" },
      { name: "Staff Nurse",              slug: "staff-nurse" },
      { name: "ANM Nurse",                slug: "anm-nurse" },
      { name: "GNM Nurse",                slug: "gnm-nurse" },
      { name: "B.Sc. Nurse",              slug: "bsc-nurse" },
      { name: "Semi Nurse",               slug: "semi-nurse" },
      { name: "GDA",                      slug: "gda" },
      { name: "Patient Care Attendant",   slug: "patient-care-attendant" },
      { name: "Elder Care Attendant",     slug: "elder-care-attendant" },
      { name: "Baby Care Attendant",      slug: "baby-care-attendant" },
      { name: "Nanny",                    slug: "nanny" },
      { name: "Babysitter",               slug: "babysitter" },
      { name: "Japa Maid",                slug: "japa-maid" },
      { name: "Mother Care",              slug: "mother-care" },
      { name: "Ward Boy",                 slug: "ward-boy" },
      { name: "Physiotherapist",          slug: "physiotherapist" },
      { name: "Occupational Therapist",   slug: "occupational-therapist" },
      { name: "Speech Therapist",         slug: "speech-therapist" },
      { name: "Dietitian",                slug: "dietitian" },
      { name: "Lab Technician",           slug: "lab-technician" },
      { name: "ECG Technician",           slug: "ecg-technician" },
      { name: "Phlebotomist",             slug: "phlebotomist" },
      { name: "Pharmacy Medical Attendant", slug: "pharmacy-medical-attendant" },
      { name: "Medical Escort",           slug: "medical-escort" },
    ],
  },
  {
    name: "Medical Equipment",
    slug: "medical-equipment",
    subs: [
      { name: "Oxygen Cylinder",      slug: "oxygen-cylinder" },
      { name: "Oxygen Concentrator",  slug: "oxygen-concentrator" },
      { name: "ICU Setup",            slug: "icu-setup" },
      { name: "Hospital Bed",         slug: "hospital-bed" },
      { name: "Wheelchair",           slug: "wheelchair" },
      { name: "Walker",               slug: "walker" },
      { name: "Air Mattress",         slug: "air-mattress" },
      { name: "BiPAP",                slug: "bipap" },
      { name: "CPAP",                 slug: "cpap" },
      { name: "Suction Machine",      slug: "suction-machine" },
      { name: "Nebulizer",            slug: "nebulizer" },
      { name: "Patient Monitor",      slug: "patient-monitor" },
      { name: "Infusion Pump",        slug: "infusion-pump" },
    ],
  },
  {
    name: "Domestic & Household Services",
    slug: "domestic",
    subs: [
      { name: "Maid",                 slug: "maid" },
      { name: "Part Time Maid",       slug: "part-time-maid" },
      { name: "Full Time Maid",       slug: "full-time-maid" },
      { name: "Live In Maid [24 hours]", slug: "live-in-maid" },
      { name: "Cleaning Maid",        slug: "cleaning-maid" },
      { name: "Deep Cleaning Staff",  slug: "deep-cleaning-staff" },
      { name: "Housekeeper",          slug: "housekeeper" },
      { name: "Housekeeping Staff",   slug: "housekeeping-staff" },
      { name: "Cook",                 slug: "cook" },
      { name: "Chef",                 slug: "chef" },
      { name: "Home Chef",            slug: "home-chef" },
      { name: "Kitchen Helper",       slug: "kitchen-helper" },
      { name: "Butler",               slug: "butler" },
      { name: "Laundry Staff",        slug: "laundry-staff" },
      { name: "Ironing Staff",        slug: "ironing-staff" },
      { name: "Dishwasher",           slug: "dishwasher" },
      { name: "Home Manager",         slug: "home-manager" },
      { name: "Caretaker",            slug: "caretaker" },
      { name: "Couple Caretaker (Husband-Wife)", slug: "couple-caretaker" },
      { name: "Pantry Helper",        slug: "pantry-helper-domestic" },
    ],
  },
  {
    name: "Home & Estate Care (Couple Services)",
    slug: "home-estate-care-couple",
    subs: [
      { name: "Husband & Wife Couple",     slug: "husband-wife-couple" },
      { name: "Caretaker Couple",          slug: "caretaker-couple" },
      { name: "Farm Couple",               slug: "farm-couple" },
      { name: "Resort Couple",             slug: "resort-couple" },
      { name: "Housekeeping Couple",       slug: "housekeeping-couple" },
      { name: "Villa / Farmhouse Caretaker", slug: "villa-farmhouse-caretaker" },
      { name: "Live-in Couple Staff",      slug: "live-in-couple-staff" },
    ],
  },
  {
    name: "Driver Services",
    slug: "driver",
    subs: [
      { name: "Personal Driver",       slug: "personal-driver" },
      { name: "Family Driver",         slug: "family-driver" },
      { name: "Office Driver",         slug: "office-driver" },
      { name: "School Driver",         slug: "school-driver" },
      { name: "Commercial Driver",     slug: "commercial-driver" },
      { name: "Delivery Driver",       slug: "delivery-driver" },
      { name: "Ambulance Driver",      slug: "ambulance-driver" },
      { name: "Truck Driver",          slug: "truck-driver" },
      { name: "Bus Driver",            slug: "bus-driver" },
      { name: "Heavy Vehicle Driver",  slug: "heavy-vehicle-driver" },
      { name: "Chauffeur",             slug: "chauffeur" },
    ],
  },
  {
    name: "Security Services",
    slug: "security",
    subs: [
      { name: "Security Guard",         slug: "security-guard" },
      { name: "Armed Guard",            slug: "armed-guard" },
      { name: "Unarmed Guard",          slug: "unarmed-guard" },
      { name: "Watchman",               slug: "watchman" },
      { name: "Gatekeeper",             slug: "gatekeeper" },
      { name: "Bouncer",                slug: "bouncer" },
      { name: "Bodyguard",              slug: "bodyguard" },
      { name: "Gunman",                 slug: "gunman" },
      { name: "CCTV Monitoring Staff",  slug: "cctv-monitoring-staff" },
    ],
  },
  {
    name: "Office Support Staff",
    slug: "office-support",
    subs: [
      { name: "Receptionist",            slug: "receptionist" },
      { name: "Social Media Manager",    slug: "social-media-manager" },
      { name: "Digital Marketing",       slug: "digital-marketing" },
      { name: "Front Desk Executive",    slug: "front-desk-executive" },
      { name: "Telecaller",              slug: "telecaller" },
      { name: "Customer Care Executive", slug: "customer-care-executive" },
      { name: "Data Entry Operator",     slug: "data-entry-operator" },
      { name: "Computer Operator",       slug: "computer-operator" },
      { name: "Document Executive",      slug: "document-executive" },
      { name: "Office Assistant",        slug: "office-assistant" },
      { name: "Office Coordinator",      slug: "office-coordinator" },
      { name: "Admin Executive",         slug: "admin-executive" },
      { name: "Personal Assistant",      slug: "personal-assistant" },
      { name: "Executive Assistant",     slug: "executive-assistant" },
      { name: "Office Boy",              slug: "office-boy" },
      { name: "Office Girl",             slug: "office-girl" },
      { name: "Pantry Helper",           slug: "pantry-helper-office" },
      { name: "Peon",                    slug: "peon" },
    ],
  },
  {
    name: "BPO / Call Centre",
    slug: "bpo-call-centre",
    subs: [
      { name: "Voice Process",          slug: "voice-process" },
      { name: "Non Voice",              slug: "non-voice" },
      { name: "Chat Support",           slug: "chat-support" },
      { name: "Email Support",          slug: "email-support" },
      { name: "Technical Support",      slug: "technical-support" },
      { name: "International Process",  slug: "international-process" },
    ],
  },
  {
    name: "Business & Corporate",
    slug: "business-corporate",
    subs: [
      { name: "HR Executive",                   slug: "hr-executive" },
      { name: "Recruiter",                      slug: "recruiter" },
      { name: "Payroll Executive",              slug: "payroll-executive" },
      { name: "Accountant",                     slug: "accountant" },
      { name: "Cashier",                        slug: "cashier-business" },
      { name: "Sales Executive",                slug: "sales-executive" },
      { name: "Business Development Executive", slug: "bde" },
      { name: "Marketing Executive",            slug: "marketing-executive" },
      { name: "Field Executive",                slug: "field-executive" },
      { name: "Collection Executive",           slug: "collection-executive" },
      { name: "Customer Support Executive",     slug: "customer-support-executive" },
      { name: "Team Leader",                    slug: "team-leader" },
      { name: "Supervisor",                     slug: "supervisor" },
      { name: "Branch Manager",                 slug: "branch-manager" },
      { name: "Operations Manager",             slug: "operations-manager" },
    ],
  },
  {
    name: "IT & Software",
    slug: "it-software",
    subs: [
      { name: "Software Engineer",        slug: "software-engineer" },
      { name: "Software Developer",       slug: "software-developer" },
      { name: "Web Developer",            slug: "web-developer" },
      { name: "Frontend Developer",       slug: "frontend-developer" },
      { name: "Backend Developer",        slug: "backend-developer" },
      { name: "Full Stack Developer",     slug: "full-stack-developer" },
      { name: "Mobile App Developer",     slug: "mobile-app-developer" },
      { name: "Android Developer",        slug: "android-developer" },
      { name: "iOS Developer",            slug: "ios-developer" },
      { name: "Flutter Developer",        slug: "flutter-developer" },
      { name: "WordPress Developer",      slug: "wordpress-developer" },
      { name: "UI Designer",              slug: "ui-designer" },
      { name: "UX Designer",              slug: "ux-designer" },
      { name: "Graphic Designer",         slug: "graphic-designer" },
      { name: "Motion Graphic Designer",  slug: "motion-graphic-designer" },
      { name: "Video Editor",             slug: "video-editor" },
      { name: "Animator",                 slug: "animator" },
      { name: "AI Engineer",              slug: "ai-engineer" },
      { name: "Machine Learning Engineer", slug: "ml-engineer" },
      { name: "Data Analyst",             slug: "data-analyst" },
      { name: "Data Scientist",           slug: "data-scientist" },
      { name: "DevOps Engineer",          slug: "devops-engineer" },
      { name: "Cloud Engineer",           slug: "cloud-engineer" },
      { name: "Cyber Security Engineer",  slug: "cyber-security-engineer" },
      { name: "QA Engineer",              slug: "qa-engineer" },
      { name: "Network Engineer",         slug: "network-engineer" },
      { name: "Database Administrator",   slug: "dba" },
    ],
  },
  {
    name: "Technical Services",
    slug: "technical",
    subs: [
      { name: "Electrician",                 slug: "electrician" },
      { name: "Plumber",                     slug: "plumber" },
      { name: "Carpenter",                   slug: "carpenter" },
      { name: "Painter",                     slug: "painter-technical" },
      { name: "Mason",                       slug: "mason-technical" },
      { name: "POP Worker",                  slug: "pop-worker" },
      { name: "Tile Worker",                 slug: "tile-worker" },
      { name: "Marble Worker",               slug: "marble-worker" },
      { name: "Welder",                      slug: "welder-technical" },
      { name: "Fabricator",                  slug: "fabricator-technical" },
      { name: "Aluminium Worker",            slug: "aluminium-worker" },
      { name: "Glass Installer",             slug: "glass-installer" },
      { name: "AC Technician",               slug: "ac-technician" },
      { name: "Refrigerator Technician",     slug: "refrigerator-technician" },
      { name: "Washing Machine Technician",  slug: "washing-machine-technician" },
      { name: "Microwave Technician",        slug: "microwave-technician" },
      { name: "TV Technician",               slug: "tv-technician" },
      { name: "RO Technician",               slug: "ro-technician" },
      { name: "Water Purifier Technician",   slug: "water-purifier-technician" },
      { name: "CCTV Technician",             slug: "cctv-technician" },
      { name: "Solar Technician",            slug: "solar-technician" },
      { name: "Lift Technician",             slug: "lift-technician" },
    ],
  },
  {
    name: "Hospitality & Hotel",
    slug: "hospitality",
    subs: [
      { name: "Waiter",              slug: "waiter" },
      { name: "Steward",             slug: "steward" },
      { name: "Captain",             slug: "captain" },
      { name: "Restaurant Manager",  slug: "restaurant-manager" },
      { name: "Barista",             slug: "barista" },
      { name: "Bartender",           slug: "bartender" },
      { name: "Pantry Staff",        slug: "pantry-staff" },
      { name: "Kitchen Staff",       slug: "kitchen-staff" },
      { name: "Restaurant Cashier",  slug: "restaurant-cashier" },
      { name: "Hotel Receptionist",  slug: "hotel-receptionist" },
      { name: "Housekeeping Staff",  slug: "housekeeping-staff-hospitality" },
      { name: "Room Service Staff",  slug: "room-service-staff" },
    ],
  },
  {
    name: "Construction & Civil",
    slug: "construction-civil",
    subs: [
      { name: "Civil Engineer",     slug: "civil-engineer" },
      { name: "Site Engineer",      slug: "site-engineer" },
      { name: "Site Supervisor",    slug: "site-supervisor" },
      { name: "Architect",          slug: "architect" },
      { name: "Interior Designer",  slug: "interior-designer" },
      { name: "Quantity Surveyor",  slug: "quantity-surveyor" },
      { name: "Surveyor",           slug: "surveyor" },
      { name: "Mason",              slug: "mason-construction" },
      { name: "Helper",             slug: "helper-construction" },
      { name: "Steel Fixer",        slug: "steel-fixer" },
      { name: "Scaffolder",         slug: "scaffolder" },
      { name: "Bar Bender",         slug: "bar-bender" },
      { name: "Concrete Worker",    slug: "concrete-worker" },
    ],
  },
  {
    name: "Mechanical & Industrial",
    slug: "mechanical-industrial",
    subs: [
      { name: "Fitter",                      slug: "fitter" },
      { name: "Turner",                      slug: "turner" },
      { name: "Machinist",                   slug: "machinist" },
      { name: "CNC Operator",                slug: "cnc-operator-mechanical" },
      { name: "Lathe Operator",              slug: "lathe-operator-mechanical" },
      { name: "Maintenance Technician",      slug: "maintenance-technician" },
      { name: "Hydraulic Technician",        slug: "hydraulic-technician" },
      { name: "Pneumatic Technician",        slug: "pneumatic-technician" },
      { name: "Plant Maintenance Technician", slug: "plant-maintenance-technician" },
      { name: "Welder",                      slug: "welder-mechanical" },
      { name: "Fabricator",                  slug: "fabricator-mechanical" },
      { name: "Sheet Metal Worker",          slug: "sheet-metal-worker" },
      { name: "Pipe Fitter",                 slug: "pipe-fitter" },
      { name: "Plant Operator",              slug: "plant-operator" },
      { name: "Boiler Operator",             slug: "boiler-operator" },
      { name: "Compressor Operator",         slug: "compressor-operator" },
      { name: "Quality Inspector",           slug: "quality-inspector-mechanical" },
      { name: "Quality Engineer",            slug: "quality-engineer" },
      { name: "Mechanical Helper",           slug: "mechanical-helper" },
      { name: "Industrial Helper",           slug: "industrial-helper" },
      { name: "Workshop Helper",             slug: "workshop-helper" },
    ],
  },
  {
    name: "Automobile",
    slug: "automobile",
    subs: [
      { name: "Car Mechanic",                 slug: "car-mechanic" },
      { name: "Bike Mechanic",                slug: "bike-mechanic" },
      { name: "Commercial Vehicle Mechanic",  slug: "commercial-vehicle-mechanic" },
      { name: "Auto Electrician",             slug: "auto-electrician" },
      { name: "Battery Technician",           slug: "battery-technician" },
      { name: "Wiring Technician",            slug: "wiring-technician" },
      { name: "Denting Technician",           slug: "denting-technician" },
      { name: "Painter",                      slug: "painter-automobile" },
      { name: "Polishing Technician",         slug: "polishing-technician" },
      { name: "Tyre Technician",              slug: "tyre-technician" },
      { name: "Wheel Alignment Technician",   slug: "wheel-alignment-technician" },
      { name: "Wheel Balancing Technician",   slug: "wheel-balancing-technician" },
      { name: "Service Advisor",              slug: "service-advisor" },
      { name: "Vehicle Inspector",            slug: "vehicle-inspector" },
      { name: "Car Washer",                   slug: "car-washer" },
      { name: "Car Detailer",                 slug: "car-detailer" },
      { name: "EV Technician",                slug: "ev-technician" },
      { name: "EV Charging Technician",       slug: "ev-charging-technician" },
      { name: "Battery Service Technician",   slug: "battery-service-technician" },
    ],
  },
  {
    name: "Aviation & Airport",
    slug: "aviation-airport",
    subs: [
      { name: "Ground Staff",                 slug: "ground-staff" },
      { name: "Ramp Staff",                   slug: "ramp-staff" },
      { name: "Baggage Handler",              slug: "baggage-handler" },
      { name: "Cargo Loader",                 slug: "cargo-loader" },
      { name: "Check-in Executive",           slug: "check-in-executive" },
      { name: "Boarding Gate Executive",      slug: "boarding-gate-executive" },
      { name: "Customer Service Executive",   slug: "customer-service-executive-aviation" },
      { name: "Reservation Executive",        slug: "reservation-executive" },
      { name: "Cargo Executive",              slug: "cargo-executive" },
      { name: "Warehouse Assistant",          slug: "warehouse-assistant" },
      { name: "Cargo Supervisor",             slug: "cargo-supervisor" },
      { name: "Airport Driver",               slug: "airport-driver" },
      { name: "Shuttle Bus Driver",           slug: "shuttle-bus-driver" },
      { name: "Equipment Operator",           slug: "equipment-operator" },
      { name: "Airport Security",             slug: "airport-security" },
      { name: "Security Screener",            slug: "security-screener" },
      { name: "Fire & Safety Staff",          slug: "fire-safety-staff" },
      { name: "Aircraft Cleaner",             slug: "aircraft-cleaner" },
      { name: "Aircraft Technician",          slug: "aircraft-technician" },
      { name: "Aircraft Maintenance Technician (AME Assistant)", slug: "ame-assistant" },
    ],
  },
  {
    name: "Retail & Store",
    slug: "retail-store",
    subs: [
      { name: "Store Manager",       slug: "store-manager" },
      { name: "Salesman",            slug: "salesman" },
      { name: "Salesgirl",           slug: "salesgirl" },
      { name: "Cashier",             slug: "cashier-retail" },
      { name: "Billing Executive",   slug: "billing-executive" },
      { name: "Store Keeper",        slug: "store-keeper" },
      { name: "Inventory Executive", slug: "inventory-executive" },
      { name: "Picker",              slug: "picker-retail" },
      { name: "Packer",              slug: "packer-retail" },
      { name: "Merchandiser",        slug: "merchandiser" },
    ],
  },
  {
    name: "Logistics & Warehouse",
    slug: "logistics-warehouse",
    subs: [
      { name: "Loader",             slug: "loader" },
      { name: "Unloader",           slug: "unloader" },
      { name: "Warehouse Helper",   slug: "warehouse-helper" },
      { name: "Picker",             slug: "picker-warehouse" },
      { name: "Packer",             slug: "packer-warehouse" },
      { name: "Sorting Staff",      slug: "sorting-staff" },
      { name: "Dispatch Executive", slug: "dispatch-executive" },
      { name: "Inventory Staff",    slug: "inventory-staff" },
      { name: "Forklift Operator",  slug: "forklift-operator" },
    ],
  },
  {
    name: "Factory & Manufacturing",
    slug: "factory-manufacturing",
    subs: [
      { name: "Machine Operator",  slug: "machine-operator" },
      { name: "Production Worker", slug: "production-worker" },
      { name: "Assembly Worker",   slug: "assembly-worker" },
      { name: "Packaging Worker",  slug: "packaging-worker" },
      { name: "Quality Inspector", slug: "quality-inspector-factory" },
      { name: "CNC Operator",      slug: "cnc-operator-factory" },
      { name: "Lathe Operator",    slug: "lathe-operator-factory" },
      { name: "Helper",            slug: "factory-helper" },
      { name: "Shift Supervisor",  slug: "shift-supervisor" },
    ],
  },
  {
    name: "Agriculture & Farm",
    slug: "agriculture-farm",
    subs: [
      { name: "Farm Worker",         slug: "farm-worker" },
      { name: "Tractor Driver",      slug: "tractor-driver" },
      { name: "Harvester Operator",  slug: "harvester-operator" },
      { name: "Dairy Worker",        slug: "dairy-worker" },
      { name: "Poultry Worker",      slug: "poultry-worker" },
      { name: "Gardener",            slug: "gardener" },
      { name: "Plant Care Staff",    slug: "plant-care-staff" },
      { name: "Irrigation Operator", slug: "irrigation-operator" },
    ],
  },
  {
    name: "Event & Hospitality Support",
    slug: "event-support",
    subs: [
      { name: "Event Helper",      slug: "event-helper" },
      { name: "Event Coordinator", slug: "event-coordinator" },
      { name: "Decorator",         slug: "decorator" },
      { name: "Sound Technician",  slug: "sound-technician" },
      { name: "Light Technician",  slug: "light-technician" },
      { name: "Photographer",      slug: "photographer" },
      { name: "Videographer",      slug: "videographer" },
      { name: "Anchor",            slug: "anchor" },
      { name: "DJ",                slug: "dj" },
      { name: "Catering Staff",    slug: "catering-staff" },
    ],
  },
  {
    name: "Beauty & Wellness",
    slug: "beauty-wellness",
    subs: [
      { name: "Beautician",               slug: "beautician" },
      { name: "Makeup Artist",            slug: "makeup-artist" },
      { name: "Hair Stylist",             slug: "hair-stylist" },
      { name: "Barber",                   slug: "barber" },
      { name: "Nail Technician",          slug: "nail-technician" },
      { name: "Spa Therapist",            slug: "spa-therapist" },
      { name: "Massage Therapist",        slug: "massage-therapist" },
      { name: "Yoga Trainer",             slug: "yoga-trainer-beauty" },
      { name: "Gym Trainer",              slug: "gym-trainer" },
      { name: "Personal Fitness Trainer", slug: "personal-fitness-trainer" },
    ],
  },
  {
    name: "Education",
    slug: "education",
    subs: [
      { name: "School Teacher",                 slug: "school-teacher" },
      { name: "Home Tutor",                     slug: "home-tutor" },
      { name: "Online Tutor",                   slug: "online-tutor" },
      { name: "Online Teacher",                 slug: "online-teacher" },
      { name: "College Faculty",                slug: "college-faculty" },
      { name: "Lecturer",                       slug: "lecturer" },
      { name: "Assistant Professor",            slug: "assistant-professor" },
      { name: "Professor",                      slug: "professor" },
      { name: "Computer Trainer",               slug: "computer-trainer" },
      { name: "Coding Trainer",                 slug: "coding-trainer" },
      { name: "Software Trainer",               slug: "software-trainer" },
      { name: "Spoken English Trainer",         slug: "spoken-english-trainer" },
      { name: "IELTS Trainer",                  slug: "ielts-trainer" },
      { name: "Personality Development Trainer", slug: "personality-development-trainer" },
      { name: "Corporate Trainer",              slug: "corporate-trainer" },
      { name: "Music Teacher",                  slug: "music-teacher" },
      { name: "Dance Teacher",                  slug: "dance-teacher" },
      { name: "Art Teacher",                    slug: "art-teacher" },
      { name: "Sports Coach",                   slug: "sports-coach" },
      { name: "Yoga Trainer",                   slug: "yoga-trainer-education" },
    ],
  },
  {
    name: "Pet Care Services",
    slug: "pet-care",
    subs: [
      { name: "Dog Walker",           slug: "dog-walker" },
      { name: "Pet Groomer",          slug: "pet-groomer" },
      { name: "Pet Trainer",          slug: "pet-trainer" },
      { name: "Pet Caretaker",        slug: "pet-caretaker" },
      { name: "Pet Boarding Staff",   slug: "pet-boarding-staff" },
      { name: "Veterinary Assistant", slug: "veterinary-assistant" },
    ],
  },
  {
    name: "Cleaning & Facility Management",
    slug: "cleaning-facility",
    subs: [
      { name: "House Cleaner",           slug: "house-cleaner" },
      { name: "Office Cleaner",          slug: "office-cleaner" },
      { name: "Society Cleaner",         slug: "society-cleaner" },
      { name: "Industrial Cleaner",      slug: "industrial-cleaner" },
      { name: "Glass Cleaner",           slug: "glass-cleaner" },
      { name: "Carpet Cleaner",          slug: "carpet-cleaner" },
      { name: "Sofa Cleaner",            slug: "sofa-cleaner" },
      { name: "Water Tank Cleaner",      slug: "water-tank-cleaner" },
      { name: "Pest Control Technician", slug: "pest-control-technician" },
    ],
  },
  {
    name: "Professional Services",
    slug: "professional-services",
    subs: [
      { name: "Advocate",                    slug: "advocate" },
      { name: "Legal Advisor",               slug: "legal-advisor" },
      { name: "Chartered Accountant (CA)",   slug: "chartered-accountant" },
      { name: "Company Secretary (CS)",      slug: "company-secretary" },
      { name: "Tax Consultant",              slug: "tax-consultant" },
      { name: "GST Consultant",              slug: "gst-consultant" },
      { name: "Financial Advisor",           slug: "financial-advisor" },
      { name: "Insurance Advisor",           slug: "insurance-advisor" },
      { name: "Investment Advisor",          slug: "investment-advisor" },
      { name: "Loan Consultant",             slug: "loan-consultant" },
      { name: "Real Estate Consultant",      slug: "real-estate-consultant" },
      { name: "Property Consultant",         slug: "property-consultant" },
    ],
  },
  {
    name: "Government & NGO Services",
    slug: "government-ngo",
    subs: [
      { name: "Survey Staff",         slug: "survey-staff" },
      { name: "Enumerator",           slug: "enumerator" },
      { name: "Project Coordinator",  slug: "project-coordinator" },
      { name: "Field Investigator",   slug: "field-investigator" },
    ],
  },
  {
    name: "Repair & Maintenance Services",
    slug: "repair-maintenance",
    subs: [
      { name: "Mobile Repair Technician",       slug: "mobile-repair-technician" },
      { name: "Laptop Repair Technician",       slug: "laptop-repair-technician" },
      { name: "Desktop Computer Technician",    slug: "desktop-computer-technician" },
      { name: "TV Repair Technician",           slug: "tv-repair-technician" },
      { name: "Printer Technician",             slug: "printer-technician" },
      { name: "CCTV Repair Technician",         slug: "cctv-repair-technician" },
      { name: "AC Repair Technician",           slug: "ac-repair-technician" },
      { name: "Refrigerator Repair Technician", slug: "refrigerator-repair-technician" },
      { name: "Washing Machine Technician",     slug: "washing-machine-technician-repair" },
      { name: "Microwave Oven Technician",      slug: "microwave-oven-technician" },
      { name: "RO / Water Purifier Technician", slug: "ro-water-purifier-technician" },
      { name: "Electrician",                    slug: "electrician-repair" },
      { name: "Generator Technician",           slug: "generator-technician" },
      { name: "Inverter Technician",            slug: "inverter-technician" },
      { name: "Handyman",                       slug: "handyman" },
      { name: "Maintenance Technician",         slug: "maintenance-technician-repair" },
      { name: "Facility Maintenance Technician", slug: "facility-maintenance-technician" },
    ],
  },
];

async function main() {
  console.log("Seeding categories and subcategories...\n");

  let totalSubs = 0;

  for (const cat of SEED_DATA) {
    const category = await prisma.category.upsert({
      where:  { slug: cat.slug },
      update: { name: cat.name },
      create: { name: cat.name, slug: cat.slug },
    });

    for (const sub of cat.subs) {
      await prisma.subCategory.upsert({
        where:  { slug: sub.slug },
        update: { name: sub.name, categoryId: category.id },
        create: { name: sub.name, slug: sub.slug, categoryId: category.id },
      });
    }

    totalSubs += cat.subs.length;
    console.log(`✓ ${cat.name} (${cat.subs.length} subcategories)`);
  }

  console.log(`\nSeed complete — ${SEED_DATA.length} categories, ${totalSubs} subcategories.`);
}

main()
  .catch((e) => {
    console.error(e);
    throw e;
  })
  .finally(async () => {
    await prisma.$disconnect();
  });