import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const SEED_DATA = [
  {
    name: "Healthcare & Medical Services",
    slug: "healthcare",
    subs: [
      { name: "Visit Doctor",             slug: "visit-doctor" },
      { name: "General Physician",        slug: "general-physician" },
      { name: "Specialist Doctor",        slug: "specialist-doctor" },
      { name: "Home Nurse",               slug: "home-nurse" },
      { name: "ICU Nurse",                slug: "icu-nurse" },
      { name: "Staff Nurse",              slug: "staff-nurse" },
      { name: "ANM Nurse",                slug: "anm-nurse" },
      { name: "GNM Nurse",                slug: "gnm-nurse" },
      { name: "B.Sc. Nurse",              slug: "bsc-nurse" },
      { name: "Semi Nurse",               slug: "semi-nurse" },
      { name: "GDA",                      slug: "gda" },
      { name: "Patient Care Attendant",   slug: "patient-care-attendant" },
      { name: "Elder Care Attendant",     slug: "elder-care-attendant" },
      { name: "Baby Care Attendant",      slug: "baby-care-attendant" },
      { name: "Nanny",                    slug: "nanny" },
      { name: "Babysitter",               slug: "babysitter" },
      { name: "Japa Maid",                slug: "japa-maid" },
      { name: "Mother Care",              slug: "mother-care" },
      { name: "Ward Boy",                 slug: "ward-boy" },
      { name: "Physiotherapist",          slug: "physiotherapist" },
      { name: "Occupational Therapist",   slug: "occupational-therapist" },
      { name: "Speech Therapist",         slug: "speech-therapist" },
      { name: "Dietitian",                slug: "dietitian" },
      { name: "Lab Technician",           slug: "lab-technician" },
      { name: "ECG Technician",           slug: "ecg-technician" },
      { name: "Phlebotomist",             slug: "phlebotomist" },
      { name: "Medical Attendant",        slug: "medical-attendant" },
      { name: "Medical Escort",           slug: "medical-escort" },
      { name: "Oxygen Cylinder",          slug: "oxygen-cylinder" },
      { name: "Oxygen Concentrator",      slug: "oxygen-concentrator" },
      { name: "Hospital Bed",             slug: "hospital-bed" },
      { name: "Wheelchair",               slug: "wheelchair" },
      { name: "Walker",                   slug: "walker" },
      { name: "Air Mattress",             slug: "air-mattress" },
      { name: "BiPAP",                    slug: "bipap" },
      { name: "CPAP",                     slug: "cpap" },
      { name: "Suction Machine",          slug: "suction-machine" },
      { name: "Nebulizer",                slug: "nebulizer" },
      { name: "Patient Monitor",          slug: "patient-monitor" },
      { name: "Infusion Pump",            slug: "infusion-pump" },
    ],
  },
  {
    name: "Domestic Services",
    slug: "domestic",
    subs: [
      { name: "Maid",                 slug: "maid" },
      { name: "Part Time Maid",       slug: "part-time-maid" },
      { name: "Full Time Maid",       slug: "full-time-maid" },
      { name: "Live In Maid",         slug: "live-in-maid" },
      { name: "Cleaning Maid",        slug: "cleaning-maid" },
      { name: "Deep Cleaning Staff",  slug: "deep-cleaning-staff" },
      { name: "Housekeeper",          slug: "housekeeper" },
      { name: "Housekeeping Staff",   slug: "housekeeping-staff" },
      { name: "Cook",                 slug: "cook" },
      { name: "Chef",                 slug: "chef" },
      { name: "Home Chef",            slug: "home-chef" },
      { name: "Kitchen Helper",       slug: "kitchen-helper" },
      { name: "Butler",               slug: "butler" },
      { name: "Laundry Staff",        slug: "laundry-staff" },
      { name: "Ironing Staff",        slug: "ironing-staff" },
      { name: "Dishwasher",           slug: "dishwasher" },
      { name: "Home Manager",         slug: "home-manager" },
      { name: "Caretaker",            slug: "caretaker" },
      { name: "Couple Caretaker",     slug: "couple-caretaker" },
      { name: "Pantry Helper",        slug: "pantry-helper" },
    ],
  },
  {
    name: "Child & Family Care",
    slug: "child-family-care",
    subs: [
      { name: "Babysitter",              slug: "babysitter-cfc" },
      { name: "Nanny",                   slug: "nanny-cfc" },
      { name: "Tutor",                   slug: "tutor" },
      { name: "Home Teacher",            slug: "home-teacher" },
      { name: "Play School Helper",      slug: "play-school-helper" },
      { name: "Child Companion",         slug: "child-companion" },
      { name: "Special Child Caregiver", slug: "special-child-caregiver" },
    ],
  },
  {
    name: "Driver Services",
    slug: "driver",
    subs: [
      { name: "Personal Driver",       slug: "personal-driver" },
      { name: "Family Driver",         slug: "family-driver" },
      { name: "Office Driver",         slug: "office-driver" },
      { name: "School Driver",         slug: "school-driver" },
      { name: "Commercial Driver",     slug: "commercial-driver" },
      { name: "Delivery Driver",       slug: "delivery-driver" },
      { name: "Ambulance Driver",      slug: "ambulance-driver" },
      { name: "Truck Driver",          slug: "truck-driver" },
      { name: "Bus Driver",            slug: "bus-driver" },
      { name: "Heavy Vehicle Driver",  slug: "heavy-vehicle-driver" },
      { name: "Chauffeur",             slug: "chauffeur" },
    ],
  },
  {
    name: "Security Services",
    slug: "security",
    subs: [
      { name: "Security Guard",         slug: "security-guard" },
      { name: "Armed Guard",            slug: "armed-guard" },
      { name: "Unarmed Guard",          slug: "unarmed-guard" },
      { name: "Watchman",               slug: "watchman" },
      { name: "Gatekeeper",             slug: "gatekeeper" },
      { name: "Bouncer",                slug: "bouncer" },
      { name: "Bodyguard",              slug: "bodyguard" },
      { name: "Gunman",                 slug: "gunman" },
      { name: "CCTV Monitoring Staff",  slug: "cctv-monitoring-staff" },
    ],
  },
  {
    name: "Office Support Staff",
    slug: "office-support",
    subs: [
      { name: "Office Boy",              slug: "office-boy" },
      { name: "Office Girl",             slug: "office-girl" },
      { name: "Peon",                    slug: "peon" },
      { name: "Receptionist",            slug: "receptionist" },
      { name: "Social Media Manager",    slug: "social-media-manager" },
      { name: "Front Desk Executive",    slug: "front-desk-executive" },
      { name: "Telecaller",              slug: "telecaller" },
      { name: "Customer Care Executive", slug: "customer-care-executive" },
      { name: "Data Entry Operator",     slug: "data-entry-operator" },
      { name: "Computer Operator",       slug: "computer-operator" },
      { name: "Document Executive",      slug: "document-executive" },
      { name: "Office Assistant",        slug: "office-assistant" },
      { name: "Office Coordinator",      slug: "office-coordinator" },
      { name: "Admin Executive",         slug: "admin-executive" },
      { name: "Personal Assistant",      slug: "personal-assistant" },
      { name: "Executive Assistant",     slug: "executive-assistant" },
    ],
  },
  {
    name: "Business & Corporate",
    slug: "business-corporate",
    subs: [
      { name: "HR Executive",                   slug: "hr-executive" },
      { name: "Recruiter",                      slug: "recruiter" },
      { name: "Payroll Executive",              slug: "payroll-executive" },
      { name: "Accountant",                     slug: "accountant" },
      { name: "Cashier",                        slug: "cashier" },
      { name: "Sales Executive",                slug: "sales-executive" },
      { name: "Business Development Executive", slug: "bde" },
      { name: "Marketing Executive",            slug: "marketing-executive" },
      { name: "Field Executive",                slug: "field-executive" },
      { name: "Collection Executive",           slug: "collection-executive" },
      { name: "Customer Support Executive",     slug: "customer-support-executive" },
      { name: "Team Leader",                    slug: "team-leader" },
      { name: "Supervisor",                     slug: "supervisor" },
      { name: "Branch Manager",                 slug: "branch-manager" },
      { name: "Operations Manager",             slug: "operations-manager" },
    ],
  },
  {
    name: "IT & Software",
    slug: "it-software",
    subs: [
      { name: "Software Engineer",        slug: "software-engineer" },
      { name: "Software Developer",       slug: "software-developer" },
      { name: "Web Developer",            slug: "web-developer" },
      { name: "Frontend Developer",       slug: "frontend-developer" },
      { name: "Backend Developer",        slug: "backend-developer" },
      { name: "Full Stack Developer",     slug: "full-stack-developer" },
      { name: "Mobile App Developer",     slug: "mobile-app-developer" },
      { name: "Android Developer",        slug: "android-developer" },
      { name: "iOS Developer",            slug: "ios-developer" },
      { name: "Flutter Developer",        slug: "flutter-developer" },
      { name: "WordPress Developer",      slug: "wordpress-developer" },
      { name: "UI Designer",              slug: "ui-designer" },
      { name: "UX Designer",              slug: "ux-designer" },
      { name: "Graphic Designer",         slug: "graphic-designer" },
      { name: "Motion Graphic Designer",  slug: "motion-graphic-designer" },
      { name: "Video Editor",             slug: "video-editor" },
      { name: "Animator",                 slug: "animator" },
      { name: "AI Engineer",              slug: "ai-engineer" },
      { name: "Machine Learning Engineer", slug: "ml-engineer" },
      { name: "Data Analyst",             slug: "data-analyst" },
      { name: "Data Scientist",           slug: "data-scientist" },
      { name: "DevOps Engineer",          slug: "devops-engineer" },
      { name: "Cloud Engineer",           slug: "cloud-engineer" },
      { name: "Cyber Security Engineer",  slug: "cyber-security-engineer" },
      { name: "QA Engineer",              slug: "qa-engineer" },
      { name: "Network Engineer",         slug: "network-engineer" },
      { name: "Database Administrator",   slug: "dba" },
    ],
  },
  {
    name: "Technical Services",
    slug: "technical",
    subs: [
      { name: "Electrician",                 slug: "electrician" },
      { name: "Plumber",                     slug: "plumber" },
      { name: "Carpenter",                   slug: "carpenter" },
      { name: "Painter",                     slug: "painter" },
      { name: "Mason",                       slug: "mason" },
      { name: "POP Worker",                  slug: "pop-worker" },
      { name: "Tile Worker",                 slug: "tile-worker" },
      { name: "Marble Worker",               slug: "marble-worker" },
      { name: "Welder",                      slug: "welder" },
      { name: "Fabricator",                  slug: "fabricator" },
      { name: "Aluminium Worker",            slug: "aluminium-worker" },
      { name: "Glass Installer",             slug: "glass-installer" },
      { name: "AC Technician",               slug: "ac-technician" },
      { name: "Refrigerator Technician",     slug: "refrigerator-technician" },
      { name: "Washing Machine Technician",  slug: "washing-machine-technician" },
      { name: "Microwave Technician",        slug: "microwave-technician" },
      { name: "TV Technician",               slug: "tv-technician" },
      { name: "RO Technician",               slug: "ro-technician" },
      { name: "Water Purifier Technician",   slug: "water-purifier-technician" },
      { name: "CCTV Technician",             slug: "cctv-technician" },
      { name: "Solar Technician",            slug: "solar-technician" },
      { name: "Lift Technician",             slug: "lift-technician" },
    ],
  },
  {
    name: "Hospitality",
    slug: "hospitality",
    subs: [
      { name: "Waiter",              slug: "waiter" },
      { name: "Steward",             slug: "steward" },
      { name: "Captain",             slug: "captain" },
      { name: "Restaurant Manager",  slug: "restaurant-manager" },
      { name: "Barista",             slug: "barista" },
      { name: "Bartender",           slug: "bartender" },
      { name: "Pantry Staff",        slug: "pantry-staff" },
      { name: "Kitchen Staff",       slug: "kitchen-staff" },
      { name: "Restaurant Cashier",  slug: "restaurant-cashier" },
      { name: "Hotel Receptionist",  slug: "hotel-receptionist" },
      { name: "Room Service Staff",  slug: "room-service-staff" },
    ],
  },
  {
    name: "Retail & Store",
    slug: "retail-store",
    subs: [
      { name: "Store Manager",       slug: "store-manager" },
      { name: "Salesman",            slug: "salesman" },
      { name: "Salesgirl",           slug: "salesgirl" },
      { name: "Cashier",             slug: "cashier-retail" },
      { name: "Billing Executive",   slug: "billing-executive" },
      { name: "Store Keeper",        slug: "store-keeper" },
      { name: "Inventory Executive", slug: "inventory-executive" },
      { name: "Picker",              slug: "picker-retail" },
      { name: "Packer",              slug: "packer-retail" },
      { name: "Merchandiser",        slug: "merchandiser" },
    ],
  },
  {
    name: "Logistics & Warehouse",
    slug: "logistics-warehouse",
    subs: [
      { name: "Loader",             slug: "loader" },
      { name: "Unloader",           slug: "unloader" },
      { name: "Warehouse Helper",   slug: "warehouse-helper" },
      { name: "Picker",             slug: "picker-warehouse" },
      { name: "Packer",             slug: "packer-warehouse" },
      { name: "Sorting Staff",      slug: "sorting-staff" },
      { name: "Dispatch Executive", slug: "dispatch-executive" },
      { name: "Inventory Staff",    slug: "inventory-staff" },
      { name: "Forklift Operator",  slug: "forklift-operator" },
    ],
  },
  {
    name: "Factory & Manufacturing",
    slug: "factory-manufacturing",
    subs: [
      { name: "Machine Operator",  slug: "machine-operator" },
      { name: "Production Worker", slug: "production-worker" },
      { name: "Assembly Worker",   slug: "assembly-worker" },
      { name: "Packaging Worker",  slug: "packaging-worker" },
      { name: "Quality Inspector", slug: "quality-inspector" },
      { name: "CNC Operator",      slug: "cnc-operator" },
      { name: "Lathe Operator",    slug: "lathe-operator" },
      { name: "Helper",            slug: "factory-helper" },
      { name: "Shift Supervisor",  slug: "shift-supervisor" },
    ],
  },
  {
    name: "Agriculture & Farm",
    slug: "agriculture-farm",
    subs: [
      { name: "Farm Worker",         slug: "farm-worker" },
      { name: "Tractor Driver",      slug: "tractor-driver" },
      { name: "Harvester Operator",  slug: "harvester-operator" },
      { name: "Dairy Worker",        slug: "dairy-worker" },
      { name: "Poultry Worker",      slug: "poultry-worker" },
      { name: "Gardener",            slug: "gardener" },
      { name: "Plant Care Staff",    slug: "plant-care-staff" },
      { name: "Irrigation Operator", slug: "irrigation-operator" },
    ],
  },
  {
    name: "Event & Hospitality Support",
    slug: "event-support",
    subs: [
      { name: "Event Helper",      slug: "event-helper" },
      { name: "Event Coordinator", slug: "event-coordinator" },
      { name: "Decorator",         slug: "decorator" },
      { name: "Sound Technician",  slug: "sound-technician" },
      { name: "Light Technician",  slug: "light-technician" },
      { name: "Photographer",      slug: "photographer" },
      { name: "Videographer",      slug: "videographer" },
      { name: "Anchor",            slug: "anchor" },
      { name: "DJ",                slug: "dj" },
      { name: "Catering Staff",    slug: "catering-staff" },
    ],
  },
  {
    name: "Beauty & Wellness",
    slug: "beauty-wellness",
    subs: [
      { name: "Beautician",               slug: "beautician" },
      { name: "Makeup Artist",            slug: "makeup-artist" },
      { name: "Hair Stylist",             slug: "hair-stylist" },
      { name: "Barber",                   slug: "barber" },
      { name: "Nail Technician",          slug: "nail-technician" },
      { name: "Spa Therapist",            slug: "spa-therapist" },
      { name: "Massage Therapist",        slug: "massage-therapist" },
      { name: "Yoga Trainer",             slug: "yoga-trainer" },
      { name: "Gym Trainer",              slug: "gym-trainer" },
      { name: "Personal Fitness Trainer", slug: "personal-fitness-trainer" },
    ],
  },
  {
    name: "Education",
    slug: "education",
    subs: [
      { name: "Home Tutor",             slug: "home-tutor" },
      { name: "School Teacher",         slug: "school-teacher" },
      { name: "College Faculty",        slug: "college-faculty" },
      { name: "Computer Trainer",       slug: "computer-trainer" },
      { name: "Spoken English Trainer", slug: "spoken-english-trainer" },
      { name: "Music Teacher",          slug: "music-teacher" },
      { name: "Dance Teacher",          slug: "dance-teacher" },
      { name: "Art Teacher",            slug: "art-teacher" },
    ],
  },
  {
    name: "Pet Care",
    slug: "pet-care",
    subs: [
      { name: "Dog Walker",           slug: "dog-walker" },
      { name: "Pet Groomer",          slug: "pet-groomer" },
      { name: "Pet Trainer",          slug: "pet-trainer" },
      { name: "Pet Caretaker",        slug: "pet-caretaker" },
      { name: "Pet Boarding Staff",   slug: "pet-boarding-staff" },
      { name: "Veterinary Assistant", slug: "veterinary-assistant" },
    ],
  },
  {
    name: "Cleaning & Facility Management",
    slug: "cleaning-facility",
    subs: [
      { name: "House Cleaner",           slug: "house-cleaner" },
      { name: "Office Cleaner",          slug: "office-cleaner" },
      { name: "Society Cleaner",         slug: "society-cleaner" },
      { name: "Industrial Cleaner",      slug: "industrial-cleaner" },
      { name: "Glass Cleaner",           slug: "glass-cleaner" },
      { name: "Carpet Cleaner",          slug: "carpet-cleaner" },
      { name: "Sofa Cleaner",            slug: "sofa-cleaner" },
      { name: "Water Tank Cleaner",      slug: "water-tank-cleaner" },
      { name: "Pest Control Technician", slug: "pest-control-technician" },
    ],
  },
  {
    name: "Professional Services",
    slug: "professional-services",
    subs: [
      { name: "Advocate",               slug: "advocate" },
      { name: "Company Secretary",      slug: "company-secretary" },
      { name: "Chartered Accountant",   slug: "chartered-accountant" },
      { name: "Tax Consultant",         slug: "tax-consultant" },
      { name: "Insurance Advisor",      slug: "insurance-advisor" },
      { name: "Financial Advisor",      slug: "financial-advisor" },
      { name: "Loan Consultant",        slug: "loan-consultant" },
      { name: "Real Estate Consultant", slug: "real-estate-consultant" },
    ],
  },
];

async function main() {
  console.log("Seeding categories and subcategories...\n");

  let totalSubs = 0;

  for (const cat of SEED_DATA) {
    const category = await prisma.category.upsert({
      where:  { slug: cat.slug },
      update: { name: cat.name },
      create: { name: cat.name, slug: cat.slug },
    });

    for (const sub of cat.subs) {
      await prisma.subCategory.upsert({
        where:  { slug: sub.slug },
        update: { name: sub.name, categoryId: category.id },
        create: { name: sub.name, slug: sub.slug, categoryId: category.id },
      });
    }

    totalSubs += cat.subs.length;
    console.log(`✓ ${cat.name} (${cat.subs.length} subcategories)`);
  }

  console.log(`\nSeed complete — ${SEED_DATA.length} categories, ${totalSubs} subcategories.`);
}

main()
  .catch((e) => {
    console.error(e);
    throw e;
  })
  .finally(async () => {
    await prisma.$disconnect();
  });